apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-app-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: exam-app
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      containers:
      - name: exam-app
        image: luisrivas35/exam-app:latest  
        ports:
        - containerPort: 3000  

---

apiVersion: v1
kind: Service
metadata:
  name: exam-app-service
spec:
  selector:
    app: exam-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000  # port Node.js app is listening on
  type: NodePort
